{{- if and (not .Values.keystorePassword.existingSecret) .Values.keystorePassword.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remote-signer.fullname" . }}-keystore-password
  labels:
    {{- include "remote-signer.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.keystorePassword.value | b64enc | quote }}
{{- end }}
