{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.secretsName" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.gatewayToken.key }}: {{ include "openclaw.gatewayTokenValue" . | quote }}
{{- end }}
