{{- if eq .Values.role "prover" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.resourceName" (dict "context" . "component" "broker") }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    aztec.network/role: prover
    aztec.network/component: prover-broker
spec:
  serviceName: {{ include "chart.resourceName" (dict "context" . "component" "broker") }}
  replicas: 1
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    {{- toYaml .Values.node.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: prover-broker
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app: prover-broker
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- tpl (toYaml .Values.initContainers | nindent 8) $ }}
      {{- end }}
      containers:
        - name: prover-broker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              start_cmd=("node" "/usr/src/yarn-project/aztec/dest/bin/index.js" "start" "--prover-broker")
              {{- if .Values.network }}
              start_cmd+=("--network" "{{ .Values.network }}")
              {{- end }}
              "${start_cmd[@]}"
          startupProbe:
            httpGet:
              path: /status
              port: {{ .Values.service.httpPort }}
            periodSeconds: {{ .Values.node.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.node.startupProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.service.httpPort }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.node.storage.dataDirectory }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              value: prover-broker
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.network }}
            - name: NETWORK
              value: "{{ .Values.network }}"
            {{- else }}
            - name: REGISTRY_CONTRACT_ADDRESS
              value: "{{ .Values.customNetwork.registryContractAddress }}"
            - name: L1_CHAIN_ID
              value: "{{ .Values.customNetwork.l1ChainId }}"
            - name: SLASH_FACTORY_ADDRESS
              value: "{{ .Values.customNetwork.slashFactoryAddress }}"
            - name: FEE_ASSET_HANDLER_CONTRACT_ADDRESS
              value: "{{ .Values.customNetwork.feeAssetHandlerContractAddress }}"
            {{- end }}
            - name: NODE_OPTIONS
              value: {{ join " " .Values.node.nodeJsOptions | quote }}
            - name: AZTEC_PORT
              value: "{{ .Values.service.httpPort }}"
            - name: LOG_LEVEL
              value: "{{ .Values.node.logLevel }}"
            - name: LOG_JSON
              value: "1"
            {{- if gt (len .Values.node.l1ExecutionUrls) 0 }}
            - name: ETHEREUM_HOSTS
              value: {{ join "," .Values.node.l1ExecutionUrls | quote }}
            {{- end }}
            - name: DATA_DIRECTORY
              value: {{ .Values.node.storage.dataDirectory | quote }}
            {{- if or (eq (include "chart.monitoringEnabled" .) "true") .Values.node.metrics.otelCollectorEndpoint }}
            - name: OTEL_EXCLUDE_METRICS
              value: {{ .Values.node.metrics.otelExcludeMetrics | quote }}
            {{- if eq (include "chart.monitoringEnabled" .) "true" }}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "http://{{ include "chart.resourceName" . }}-otel-collector:4318/v1/metrics"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://{{ include "chart.resourceName" . }}-otel-collector:4318/v1/traces"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://{{ include "chart.resourceName" . }}-otel-collector:4318/v1/logs"
            {{- else }}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "{{ .Values.node.metrics.otelCollectorEndpoint }}/v1/metrics"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "{{ .Values.node.metrics.otelCollectorEndpoint }}/v1/traces"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "{{ .Values.node.metrics.otelCollectorEndpoint }}/v1/logs"
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: http-rpc
            {{- if .Values.service.admin.enabled }}
            - containerPort: {{ .Values.service.admin.port }}
              name: admin
            {{- end }}
          resources:
            {{- if .Values.prover.broker.resources }}
            {{- toYaml .Values.prover.broker.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.node.resources | nindent 12 }}
            {{- end }}
  {{- if not .Values.persistence.enabled }}
      volumes:
        - name: storage
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        {{- toYaml .Values.persistence.annotations | nindent 10 }}
    spec:
      accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 12 }}
      resources:
        requests:
          storage: {{ .Values.prover.broker.persistence.size | default .Values.persistence.size | quote}}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- if .Values.persistence.selector }}
      selector:
        {{- toYaml .Values.persistence.selector | nindent 12 }}
      {{- end }}
  {{- end }}
{{- end }}
