{{- if eq .Values.role "prover" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.resourceName" (dict "context" . "component" "node") }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    aztec.network/role: prover
    aztec.network/component: prover-node
spec:
  serviceName: {{ include "chart.resourceName" (dict "context" . "component" "node") }}
  replicas: 1
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    {{- toYaml .Values.node.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: prover-node
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app: prover-node
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- tpl (toYaml .Values.initContainers | nindent 8) $ }}
      {{- end }}
      containers:
        - name: prover-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              export P2P_IP=$(hostname -i)
              start_cmd=("node" "/usr/src/yarn-project/aztec/dest/bin/index.js" "start" "--prover-node" "--archiver")
              {{- if .Values.network }}
              start_cmd+=("--network" "{{ .Values.network }}")
              {{- end }}
              "${start_cmd[@]}"
          startupProbe:
            httpGet:
              path: /status
              port: {{ .Values.service.httpPort }}
            periodSeconds: {{ .Values.node.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.node.startupProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.service.httpPort }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.node.storage.dataDirectory }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              value: prover-node
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.network }}
            - name: NETWORK
              value: "{{ .Values.network }}"
            {{- else }}
            - name: REGISTRY_CONTRACT_ADDRESS
              value: "{{ .Values.customNetwork.registryContractAddress }}"
            - name: L1_CHAIN_ID
              value: "{{ .Values.customNetwork.l1ChainId }}"
            - name: SLASH_FACTORY_ADDRESS
              value: "{{ .Values.customNetwork.slashFactoryAddress }}"
            - name: FEE_ASSET_HANDLER_CONTRACT_ADDRESS
              value: "{{ .Values.customNetwork.feeAssetHandlerContractAddress }}"
            {{- end }}
            - name: NODE_OPTIONS
              value: {{ join " " .Values.node.nodeJsOptions | quote }}
            - name: AZTEC_PORT
              value: "{{ .Values.service.httpPort }}"
            - name: LOG_LEVEL
              value: "{{ .Values.node.logLevel }}"
            - name: LOG_JSON
              value: "1"
            - name: P2P_ENABLED
              value: "{{ .Values.service.p2p.enabled }}"
            - name: P2P_PORT
              value: "{{ .Values.service.p2p.port }}"
            - name: P2P_QUERY_FOR_IP
              value: "true"
            - name: PROVER_PUBLISHER_PRIVATE_KEY
              value: {{ .Values.prover.node.publisherPrivateKey | quote }}
            # Prover broker is running in the same deployment
            - name: PROVER_BROKER_HOST
              value: "http://{{ include "chart.resourceName" (dict "context" . "component" "broker") }}:{{ .Values.service.httpPort }}"
            {{- if .Values.prover.id }}
            - name: PROVER_ID
              value: {{ .Values.prover.id | quote }}
            {{- end }}
            {{- if gt (len .Values.node.l1ExecutionUrls) 0 }}
            - name: ETHEREUM_HOSTS
              value: {{ join "," .Values.node.l1ExecutionUrls | quote }}
            {{- end }}
            {{- if gt (len .Values.node.l1ConsensusUrls) 0 }}
            - name: L1_CONSENSUS_HOST_URLS
              value: {{ join "," .Values.node.l1ConsensusUrls | quote }}
            - name: L1_CONSENSUS_HOST_API_KEYS
              value: {{ join "," .Values.node.l1ConsensusHostApiKeys | quote }}
            - name: L1_CONSENSUS_HOST_API_KEY_HEADERS
              value: {{ join "," .Values.node.l1ConsensusHostApiKeyHeaders | quote }}
            {{- end }}
            - name: ARCHIVER_POLLING_INTERVAL_MS
              value: "10000"
            - name: DATA_DIRECTORY
              value: {{ .Values.node.storage.dataDirectory | quote }}
            - name: DATA_STORE_MAP_SIZE_KB
              value: {{ .Values.node.storage.dataStoreMapSize | quote }}
            - name: WS_DB_MAP_SIZE_KB
              value: {{ .Values.node.storage.worldStateMapSize | quote }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: http-rpc
            {{- if .Values.service.admin.enabled }}
            - containerPort: {{ .Values.service.admin.port }}
              name: admin
            {{- end }}
            {{- if .Values.service.p2p.enabled }}
            - containerPort: {{ .Values.service.p2p.port }}
              name: p2p-tcp
            - containerPort: {{ .Values.service.p2p.port }}
              protocol: UDP
              name: p2p-udp
            {{- end }}
          resources:
            {{- if .Values.prover.node.resources }}
            {{- toYaml .Values.prover.node.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.node.resources | nindent 12 }}
            {{- end }}
  {{- if not .Values.persistence.enabled }}
      volumes:
        - name: storage
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        {{- toYaml .Values.persistence.annotations | nindent 10 }}
    spec:
      accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 12 }}
      resources:
        requests:
          storage: {{ .Values.prover.node.persistence.size | default .Values.persistence.size | quote}}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- if .Values.persistence.selector }}
      selector:
        {{- toYaml .Values.persistence.selector | nindent 12 }}
      {{- end }}
  {{- end }}
{{- end }}
